const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.spokoinbli_sphere,
		C3.Plugins.Camera3D,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.HTMLElement,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.HTMLElement.Acts.SetVisible,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Camera3D.Acts.MoveAlongCameraAxis,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.ScriptsInEvents.Events_Event13_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Acts.SetMeshPoint,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.spokoinbli_sphere.Acts.SetMesh,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Cnds.EvaluateExpression
	];
};
self.C3_JsPropNameTable = [
	{Sphere: 0},
	{Graph: 0},
	{Camera3D: 0},
	{Mouse: 0},
	{InputEntry: 0},
	{Button: 0},
	{ButtonText: 0},
	{InputEntryBox: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{Tween: 0},
	{Dragger: 0},
	{Terrain: 0},
	{Frame: 0},
	{Titlebar: 0},
	{Browser: 0},
	{Input: 0},
	{HTMLElement: 0},
	{Keyboard: 0},
	{Aqum: 0},
	{CalcParts: 0},
	{Graphs: 0},
	{expr: 0},
	{x: 0},
	{y: 0},
	{z: 0},
	{param: 0}
];

self.InstanceType = {
	Graph: class extends self.ISpriteInstance {},
	Camera3D: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	InputEntry: class extends self.ISpriteFontInstance {},
	Button: class extends self.ISpriteInstance {},
	ButtonText: class extends self.ISpriteFontInstance {},
	InputEntryBox: class extends self.ISpriteInstance {},
	Dragger: class extends self.ISpriteInstance {},
	Terrain: class extends self.ITiledBackgroundInstance {},
	Frame: class extends self.ISpriteInstance {},
	Titlebar: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Input: class extends self.ITextInputInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	Keyboard: class extends self.IInstance {},
	Aqum: class extends self.ITextInstance {},
	CalcParts: class extends self.ISpriteInstance {},
	Graphs: class extends self.ISpriteInstance {}
}